### PR TITLE
Improve tests. Enhance Export and Geocoding services

### PR DESCRIPTION
**Pull request by bogdanpolak**
Small changes and improvements. Waiting for review.
If you will accept them then I'd like to add Issues:

- decouple tests from externals (unit tests in isolation), adding mocks for depenedencies on Google Gecoding Service, not load test data form external file (customer.xml)
- adding fields TField descentant objects into ColumbusModule.CustomersU
- other ideas in my mind
(In my oppinion Issues are good plece for discussing new ideas berofe implementing them)

### CODE REVIEW

**Comment by bogdanpolak** [comment]
@danieleteti: any comments on this PR?

**Comment by danieleteti** [comment]
Quite good. Let me check some integration things and then we can integrate it. However the main repo is on bitbucket.

**Comment by bogdanpolak** [comment]
@danieleteti: Pity. I found this info (main repository is on bitbucket) during development. For sure I can reproduce all changes on the bitbucket or just try to change git origin and than you can merge my PR with current main repo. Honestly, I got used to the github and the bitbucket repo looks also as dead one :-) (only REDME.md updates). Write me what to do. I'll be fine.

**Comment by danieleteti** [comment]
Yes, please, bitbucket is the main repo. We plan to close this one.

**Comment by bogdanpolak** [comment]
@danieleteti Done 🥇

**Pull request closed without merging**
